---
title: "Submission 11"
author: "Shannon Rush"
date: "July 21, 2014"
output: pdf_document
---

Fitting a generalized linear model with 60% of training data

### Load and Source
```{r source}
    source("../helpers/predictions.R")
```
```{r load_packages}
    library(caret)
    library(doMC)
```
```{r load_data, cache=TRUE}
    train <- read.csv("../../data/processed/processed_train.csv")
    test <- read.csv("../../data/original/test.csv")
```

### Create Validation
```{r create_validation, cache=TRUE}
    set.seed(1111)
    training.indices <- createDataPartition(train$Label, p=0.6, list=F)
    training <- train[training.indices,]
    validation <- train[-training.indices,]
```

### Fit GLM
```{r glm, cache=TRUE}
    predictors <- training[,setdiff(names(training),c("EventId","Label"))]
    registerDoMC(cores=4)
    glm.fit <- train(x=predictors, y=training$Label, method="glm")
```
```{r examine_glm, cache=TRUE}
    glm.fit
    str(glm.fit)
    glm.fit$finalModel
    varImp(glm.fit)
```
```{r pred_val, cache=TRUE}
    pred.val <- predict(glm.fit, validation)
    confusionMatrix(pred.val, validation$Label)
```
```{r pred_test, cache=TRUE}
    pred.test <- predict(glm.fit, test, type="prob")
    pred.final <- PrepPrediction(pred.test, test)
    WriteSubmission(pred.final, 11)
```

### Results
2.00083











