---
title: "submission 15"
author: "Shannon Rush"
date: "July 23, 2014"
output: pdf_document
---

tuning mtry

### Load and Source
```{r source}
    source("../helpers/predictions.R")
```
```{r load_packages}
    library(randomForest)
```
```{r load_data, cache=TRUE}
    train <- read.csv("../../data/original/training.csv")
    test <- read.csv("../../data/original/test.csv")
```

### Model
```{r rf}
    predictors <- train[,setdiff(names(train),c("EventId","Label","Weight"))]
    rf1.fit <- randomForest(x=predictors, y=train$Label, ntree=1000, mtry=16, do.trace=T)
```
 1000:  16.06%  9.71% 28.23%
 
```{r}
    rf2.fit <- randomForest(x=predictors, y=train$Label, ntree=1000, mtry=2, do.trace=T)
```
1000:  16.59%  8.48% 32.13%
```{r}
    set.seed(113)
    rf3.fit <- randomForest(x=predictors, y=train$Label, ntree=1000, mtry=30, do.trace=T)
```
 1000:  16.26% 10.01% 28.26%
 
```{r}
    set.seed(114)
    rf4.fit <- randomForest(x=predictors, y=train$Label, ntree=1000, mtry=8, do.trace=T)
    p <- predict(rf4.fit, test, type="prob")
    pred <- PrepPrediction(p, test)
    WriteSubmission(pred, 15)
```
1000:  16.01%  9.59% 28.33%
2.89058
```{r}
    set.seed(115)
    rf5.fit <- randomForest(x=predictors, y=train$Label, ntree=1000, mtry=4, do.trace=T)
```
1000:  16.02%  9.38% 28.77%